/** Varianti vino (scelta al click sul pulsante Vini). */
export const ORDER_WINE_VARIANTS = [
  'Vino bianco',
  'Vino rosso',
  'Vino rosato',
  'Vino sfuso bianco',
  'Vino sfuso rosso',
  'Vino sfuso rosato',
  'Prosecco',
  'Prosecco DOC',
  'Prosecco DOCG',
  'Prosecco brut',
  'Prosecco extra dry',
  'Prosecco Undici',
  'Spumante',
  'Spumante brut',
  'Spumante extra dry',
  'Franciacorta',
  'Franciacorta brut',
  'Lambrusco',
  'Lambrusco rosso',
  'Lambrusco rosato',
  'Brachetto',
  'Moscato',
  "Moscato d'Asti",
  'Asti spumante',
  'Champagne',
  'Cava',
  'Chianti',
  'Chianti Classico',
  'Chianti riserva',
  'Brunello di Montalcino',
  'Rosso di Montalcino',
  'Barolo',
  'Barbaresco',
  'Amarone della Valpolicella',
  'Valpolicella',
  'Valpolicella Ripasso',
  'Ripasso',
  "Montepulciano d'Abruzzo",
  'Primitivo',
  "Nero d'Avola",
  'Morellino di Scansano',
  'Vino Nobile di Montepulciano',
  "Barbera d'Alba",
  "Barbera d'Asti",
  'Dolcetto',
  'Nebbiolo',
  'Sangiovese',
  'Aglianico',
  'Bardolino',
  'Etna Rosso',
  'Cannonau',
  'Negroamaro',
  'Salice Salentino',
  "Cerasuolo d'Abruzzo",
  'Soave',
  'Pinot Grigio',
  'Pinot Grigio delle Venezie',
  'Gavi',
  'Vermentino',
  'Lugana',
  'Friulano',
  'Trebbiano',
  'Verdicchio',
  'Falanghina',
  'Fiano di Avellino',
  'Greco di Tufo',
  'Pecorino',
  'Catarratto',
  'Etna Bianco',
  'Orvieto',
  'Frascati',
  'Est! Est!! Est!!!',
  'Custoza',
  'Chiaretto',
  'Rosato di Salento',
  'Chardonnay',
  'Sauvignon Blanc',
  'Pinot Bianco',
  'Pinot Nero',
  'Merlot',
  'Cabernet Sauvignon',
  'Cabernet Franc',
  'Syrah',
  'Malbec',
  'Riesling',
  'Gewürztraminer',
  'Bordeaux rosso',
  'Bordeaux bianco',
  'Borgogna rosso',
  'Borgogna bianco',
  'Rioja',
  'Ribera del Duero',
  'Châteauneuf-du-Pape',
  'Vino dolce',
  'Passito',
  'Vin Santo',
  'Marsala',
  'Porto',
  'Sherry',
]

export const ORDER_BEER_VARIANTS = [
  'Birra chiara',
  'Birra rossa',
  'Birra bionda',
  'Birra scura',
  'Birra artigianale',
  'Birra analcolica',
  'Birra alla spina',
  'Birra alla spina analcolica',
  'Peroni',
  'Nastro Azzurro',
  'Moretti',
  'Moretti La Rossa',
  'Moretti Zero',
  'Ichnusa',
  'Raffo',
  'Ceres',
  'Ceres Strong',
  'Angelo Poretti',
  'Menabrea',
  'Forst',
  'Dreher',
  'Heineken',
  'Heineken Zero',
  "Beck's",
  'Corona',
  'Budweiser',
  'Guinness',
  'Paulaner',
  'Franziskaner',
  'Leffe bionda',
  'Leffe bruna',
  "Tennent's",
  'Carlsberg',
  'Stella Artois',
  'Tiger',
  'Asahi',
  'Krombacher',
  'Warsteiner',
  'Birra del Borgo',
]

export const ORDER_ICE_CREAM_VARIANTS = [
  'Gelato fiordilatte',
  'Gelato crema',
  'Gelato vaniglia',
  'Gelato cioccolato',
  'Gelato cioccolato fondente',
  'Gelato cioccolato al latte',
  'Gelato cioccolato bianco',
  'Gelato stracciatella',
  'Gelato nocciola',
  'Gelato pistacchio',
  'Gelato mandorla',
  'Gelato cocco',
  'Gelato caffè',
  'Gelato tiramisù',
  'Gelato zabaione',
  'Gelato amarena',
  'Gelato visciole',
  'Gelato fragola',
  'Gelato lampone',
  'Gelato mirtillo',
  'Gelato frutti di bosco',
  'Gelato limone',
  'Gelato arancia',
  'Gelato mandarino',
  'Gelato mango',
  'Gelato ananas',
  'Gelato melone',
  'Gelato pesca',
  'Gelato albicocca',
  'Gelato banana',
  'Gelato fico',
  'Gelato castagna',
  'Gelato torroncino',
  'Gelato biscotto',
  'Gelato cookies',
  'Gelato menta',
  'Gelato menta e cioccolato',
  'Gelato ricotta e fichi',
  'Gelato ricotta e visciole',
  'Gelato panna cotta',
  'Gelato cannella',
  'Gelato caramello',
  'Gelato salted caramel',
  'Gelato kinder',
  'Gelato nutella',
  'Gelato after eight',
  'Gelato limone e basilico',
  'Gelato yogurt',
  'Gelato yogurt ai frutti di bosco',
  'Gelato senza lattosio',
  'Gelato senza zucchero',
  'Gelato vegano',
  'Sorbetto limone',
  'Sorbetto fragola',
  'Sorbetto mango',
  'Sorbetto frutti di bosco',
  'Sorbetto melone',
  'Sorbetto pesca',
  'Granita limone',
  'Granita caffè',
  'Granita mandorla',
]

export const ORDER_ICE_VARIANTS = [
  'Ghiaccio cubetti',
  'Ghiaccio tritato',
  'Ghiaccio in busta',
  'Ghiaccio secco',
]

export const ORDER_MEAT_VARIANTS = [
  'Pollo',
  'Petto di pollo',
  'Cosce di pollo',
  'Pollo intero',
  'Manzo',
  'Manzo macinato',
  'Macinato bovino scelto',
  'Bistecca',
  'Controfiletto',
  'Fiorentina',
  'Brasato',
  'Osso buco',
  'Vitello',
  'Vitellino',
  'Scaloppine',
  'Maiale',
  'Costine di maiale',
  'Salsiccia',
  'Pancetta',
  'Guanciale',
  'Lardo',
  'Prosciutto crudo',
  'Speck',
  'Cavallo',
  'Cavallino',
  'Pecora',
  'Agnello',
  'Abbacchio',
  'Coniglio',
  'Anatra',
  'Tacchino',
  'Hamburger',
  'Macinato misto',
  'Fegato',
  'Trippa',
  'Wagyu',
]

export const ORDER_FISH_VARIANTS = [
  'Polipo',
  'Calamari',
  'Seppie',
  'Totano',
  'Moscardino',
  'Gamberi',
  'Gamberetti',
  'Mazzancolle',
  'Scampi',
  'Aragosta',
  'Astice',
  'Cozze',
  'Vongole',
  'Cannolicchi',
  'Telline',
  'Merluzzo',
  'Baccalà',
  'Stoccafisso',
  'Nasello',
  'Orata',
  'Branzino',
  'Spigola',
  'Salmone',
  'Trota',
  'Sogliola',
  'Rombo',
  'Pesce spada',
  'Tonno',
  'Ricciola',
  'Acciughe',
  'Alici',
  "Filetti di acciughe sott'olio",
  'Sardine',
  'Anguilla',
  'Filetto di pesce',
  'Pesce misto',
  'Frittura di pesce',
]

export const ORDER_LEGUME_VARIANTS = [
  'Ceci',
  'Ceci neri',
  'Lenticchie',
  'Lenticchie rosse',
  'Lenticchie verdi',
  'Lenticchie castelluccio',
  'Fagioli',
  'Fagioli cannellini',
  'Fagioli borlotti',
  'Fagioli neri',
  'Fagioli rossi',
  'Fagioli dall occhio',
  'Fagioli di Spagna',
  'Piselli secchi',
  'Fave secche',
  'Soia',
  'Azuki',
  'Lupini',
  'Cicerchie',
  'Haricot',
]

export const ORDER_CEREAL_VARIANTS = [
  'Farro',
  'Orzo',
  'Avena',
  'Miglio',
  'Quinoa',
  'Grano saraceno',
  'Mais',
  'Segale',
  'Grano tenero',
  'Grano duro',
  'Cuscus',
  'Cuscus integrale',
  'Riso',
  'Riso integrale',
  'Riso venere',
  'Riso basmati',
  'Riso arborio',
  'Riso parboiled',
  'Riso carnaroli',
  'Fiocchi di mais',
  'Fiocchi di avena',
  'Muesli',
  'Granola',
]

export const ORDER_PASTA_VARIANTS = [
  'Spaghetti',
  'Spaghettini',
  'Penne',
  'Rigatoni',
  'Fusilli',
  'Farfalle',
  'Linguine',
  'Tagliatelle',
  'Fettuccine',
  'Pappardelle',
  'Bucatini',
  'Orecchiette',
  'Mezze maniche',
  'Sedani',
  'Conchiglie',
  'Paccheri',
  'Maccheroni',
  'Lasagne',
  'Cannelloni',
  'Ravioli',
  'Tortellini',
  'Gnocchi',
  'Pasta integrale',
  'Pasta senza glutine',
  'Pasta all uovo',
]

export const ORDER_VEGETABLE_VARIANTS = [
  'Rape',
  'Pomodori',
  'Pomodori ciliegino',
  'Pomodori bianchi',
  'Pomodori datterini gialli',
  'Pelati',
  'Passata di pomodoro',
  'Zucchine',
  'Patate',
  'Cipolle',
  'Peperoni',
  'Melanzane',
  'Spinaci',
  'Fagiolini',
  'Cicoria riccia',
  'Fave',
  'Insalata',
  'Insalata mista',
  'Lattuga',
  'Rucola',
  'Carote',
  'Carote rosse',
  'Sedano',
  'Finocchi',
  'Cavolfiore',
  'Broccoli',
  'Cavolo',
  'Verza',
  'Porri',
  'Asparagi',
  'Carciofi',
  'Zucca',
  'Funghi',
  'Champignon',
  'Porcini',
  'Basilico',
  'Prezzemolo',
  'Erbe aromatiche',
  'Aglio',
  'Zenzero',
]

export const ORDER_FRUIT_VARIANTS = [
  'Banane',
  'Ciliege',
  'Fragole',
  'Anguria',
  'Mele',
  'Pere',
  'Arance',
  'Limoni',
  'Mandarini',
  'Clementine',
  'Pesche',
  'Pesche noci',
  'Albicocche',
  'Prugne',
  'Kiwi',
  'Uva bianca',
  'Uva nera',
  'Melone',
  'Meloni',
  'Melone cantalupo',
  'Ananas',
  'Mango',
  'Avocado',
  'Fichi',
  'Pompelmo',
  'Mirtilli',
  'Lamponi',
  'More',
  'Uva passa',
  'Datteri',
  'Fichi secchi',
  'Noci',
  'Mandorle',
  'Nocciole',
]

export const ORDER_DAIRY_VARIANTS = [
  'Latte intero',
  'Latte parzialmente scremato',
  'Latte scremato',
  'Latte senza lattosio',
  'Latte UHT',
  'Latte fresco',
  'Panna fresca',
  'Panna da cucina',
  'Panna spray',
  'Burro',
  'Burro tradizionale 2,5 kg',
  'Burro chiarificato',
  'Yogurt bianco',
  'Yogurt greco',
  'Yogurt greco Olympus 0%',
  'Yogurt alla frutta',
  'Yogurt intero',
  'Yogurt magro',
  'Yogurt da bere',
  'Besciamella',
  'Crema pasticcera',
  'Latte condensato',
  'Latte in polvere',
]

export const ORDER_CHEESE_VARIANTS = [
  'Mozzarella',
  'Mozzarella di bufala',
  'Burrata',
  'Stracciatella',
  'Ricotta',
  'Ricotta salata',
  'Mascarpone',
  'Parmigiano Reggiano',
  'Grana Padano',
  'Pecorino Romano',
  'Pecorino',
  'Pecorino siciliano',
  'Gorgonzola',
  'Taleggio',
  'Provolone',
  'Scamorza',
  'Caciocavallo',
  'Robiola',
  'Fontina',
  'Asiago',
  'Piave',
  'Montasio',
  'Emmental',
  'Gruyère',
  'Brie',
  'Camembert',
  'Feta',
  'Formaggio spalmabile',
  'Philadelphia',
  'Philadelphia 1,65 kg',
  'Formaggio fresco',
  'Formaggio a fette',
  'Caprino',
  'Squacquerone',
]

export const ORDER_DETERGENT_VARIANTS = [
  'Detersivo piatti',
  'Detersivo lavastoviglie',
  'Pastiglie lavastoviglie',
  'Sale lavastoviglie',
  'Brillantante lavastoviglie',
  'Detersivo pavimenti',
  'Detersivo multiuso',
  'Detersivo cucina',
  'Detersivo bagno',
  'Detersivo vetri',
  'Detersivo forno',
  'Detersivo anticalcare',
  'Detersivo acciaio',
  'Sgrassatore',
  'Sgrassatore spray',
  'Sgrassatore forno',
  'Sgrassatore barbecue',
  'Sgrassatore Sirio',
  'Disincrostante',
  'Disincrostante Sirio',
  'Detersivo lavastoviglie professionale',
  'Detergente WC',
  'Bobine di carta',
  'Carta igienica Tork SmartOne',
  'Carta igienica',
  'Asciugamani carta',
  'Sacchi biodegradabili',
  'Sacchi immondizia',
  'Brillantante',
  'Candeggina',
  'Ammoniaca',
  'Alcool denaturato',
  'Alcool etilico',
  'Alcool superfici',
  'Disinfettante',
  'Igienizzante mani',
  'Sapone liquido mani',
  'Sapone neutro',
  'Acido citrico',
  'Detergente igienizzante',
  'Detergente deodorante',
  'Spray igienizzante',
]

export const ORDER_FRUIT_JUICE_VARIANTS = [
  'Succo arancia',
  'Succo arancia rossa',
  'Succo mela',
  'Succo pesca',
  'Succo ananas',
  'Succo pera',
  'Succo ace',
  'Succo albicocca',
  'Succo limone',
  'Succo agrumi',
  'Succo pompelmo',
  'Succo uva',
  'Succo kiwi',
  'Succo mango',
  'Succo mirtillo',
  'Succo cranberry',
  'Succo frutti rossi',
  'Succo multi-frutta',
  'Succo pomodoro',
]

export const ORDER_COFFEE_VARIANTS = [
  'Caffè Supremo',
  'Caffè in grani',
  'Caffè macinato',
  'Caffè capsule',
  'Caffè cialde',
  'Caffè monodose',
  'Caffè miscela bar',
  'Caffè arabica',
  'Caffè robusta',
  'Caffè per moka',
  'Caffè espresso bar',
  'Caffè decaffeinato',
  'Caffè Decaffeinato in grani',
  'Caffè solubile',
  'Caffè ginseng',
]

export const ORDER_GINSENG_VARIANTS = [
  'Ginseng solubile',
  'Ginseng in polvere',
  'Ginseng monodose',
  'Ginseng macchina da bar',
  'Ginseng con zucchero',
  'Ginseng decaffeinato',
  'Caffè ginseng',
]

export const ORDER_TEA_INFUSION_VARIANTS = [
  'Frutti rossi della salute',
  'Tè verde',
  'Tè nero',
  'Tè alla menta',
  'Tè alla camomilla',
  'Tè alla melissa',
  'Tè alla frutta',
  'Tè ai frutti di bosco',
  'Infuso zenzero e limone',
  'Infuso rooibos',
  'Infuso drenante',
  'Infuso digestivo',
  'Infuso rilassante',
  'Tisana',
  'Tisana alle erbe',
  'Orzo solubile',
  'Orzo in grani',
]

export const ORDER_BAR_ACCESSORIES_VARIANTS = [
  'Bicchieri di carta 165 ml',
  'Bicchieri di carta 200 ml',
  'Bicchieri di carta 300 ml',
  'Bicchieri di carta 400 ml',
  'Bicchieri plastica',
  'Coperchi bicchieri',
  'Palette in legno',
  'Cannucce',
  'Cannucce biodegradabili',
  'Bustine zucchero',
  'Zuccherini',
  'Tovaglioli bar',
  'Portabicchieri',
  'Kit pulizia macchina caffè',
  'Decalcificante macchina caffè',
  'Filtri macchina caffè',
  'French Press da 300 ml',
  'French Press da 350 ml',
  'French Press da 600 ml',
  'Caffettiera moka',
  'Cioccolato in polvere bar',
  'Panna spray',
  'Asciuagamani bar',
]

export const ORDER_CHIPS_VARIANTS = [
  'Patatine San Carlo classica',
  'Patatine San Carlo wavy',
  'Patatine San Carlo light',
  'Patatine San Carlo rustiche',
  'Patatine San Carlo grigliate',
  'Patatine San Carlo lime e pepe rosa',
  'Patatine San Carlo senza glutine',
  'Patatine San Carlo junior',
  "Patatine Lay's classica",
  "Patatine Lay's paprika",
  'Patatine Pringles original',
  'Patatine Amica Chips',
  'Patatine artigianali',
  'Tortilla Chips al formaggio',
  'Tortilla Chips BBQ',
]

export const ORDER_SALUMI_VARIANTS = [
  'Prosciutto crudo',
  'Prosciutto cotto',
  'Speck',
  'Bresaola',
  'Pancetta',
  'Guanciale',
  'Lardo',
  'Mortadella',
  'Salame',
  'Salame Milano',
  'Salame Napoli',
  'Coppa',
  'Lonza',
  'Capocollo',
  'Porchetta',
  'Wurstel',
  'Salsiccia',
  'Cotechino',
  'Zampone',
  'Lardo stagionato',
]

export const ORDER_MIELE_VARIANTS = [
  'Miele millefiori',
  'Miele acacia',
  'Miele castagno',
  'Miele di eucalipto',
  'Miele di tiglio',
  'Miele liquido',
  'Miele in favo',
]

export const ORDER_BEVANDE_VARIANTS = [
  'Acqua naturale',
  'Acqua frizzante',
  'Acqua Santo Stefano',
  'Cocktail San Pellegrino',
  'Bibita cola',
  'Bibita arancia',
  'Bibita limone',
  'Bibita gassata',
  'Bibita analcolica',
  'Succo di frutta',
  'Succo arancia',
  'Succo mela',
  'Succo pera',
  'Succo pompelmo',
  'Nettare',
  'Tè freddo',
  'Energy drink',
  'Bevanda vegetale',
  'Sciroppo',
]

export const ORDER_GASTRONOMIA_VARIANTS = [
  'Friselline alla curcuma',
  'Taralli al calzone',
  'Carpaccio di finocchi',
  'Carpaccio di zucchine',
  'Carpaccio di carote',
  'Carpaccio di barbabietola',
  'Antipasto misto',
  'Olive ascolane',
  'Olive verdi denocciolate',
  'Olive nere',
  'Caponata di melanzane',
  'Melanzane sott\'olio',
  'Peperoni sott\'olio',
  'Zucchine sott\'olio',
  'Funghi trifolati',
  'Crema di peperoni',
  'Paté di olive',
  'Hummus',
  'Bruschette',
  'Focaccia barese',
  'Panzerotti',
  'Rustico leccese',
  'Pittule',
  'Involtini di peperoni',
  'Verdure grigliate',
  'Insalata di mare',
  'Insalata di polpo',
  'Insalata di baccalà',
]

export const ORDER_PUGLIA_VARIANTS = [
  'Friselli',
  'Friselline',
  'Friselline alla curcuma',
  'Taralli',
  'Taralli al finocchio',
  'Taralli al peperoncino',
  'Taralli al calzone',
  'Orecchiette fresche',
  'Cavatelli freschi',
  'Sagne ncannulate',
  'Caciocavallo podolico',
  'Canestrato pugliese',
  'Burrata',
  'Stracciatella',
  'Scamorza',
  'Ricotta forte',
  'Lampascioni sott\'olio',
  'Cime di rapa sott\'olio',
  'Olive nere schiacciate',
  'Olio extravergine pugliese',
  'Aceto di vino pugliese',
  'Mostarda di fichi',
  'Confettura di fichi',
  'Confettura di ciliegie',
  'Confettura di arance',
  'Pomodori secchi sott\'olio',
  'Carciofi sott\'olio',
  'Sottaceti misti',
  'Panzerotti pugliesi',
  'Focaccia pugliese',
]

export const ORDER_CAN_VARIANTS = [
  'Coca-Cola',
  'Coca-Cola Zero',
  'Coca-Cola Light',
  'Coca-Cola 33 cl',
  'Fanta arancia',
  'Fanta limone',
  'Sprite',
  'Pepsi',
  'Pepsi Max',
  'Aranciata',
  'Aranciata bitter',
  'Chinotto',
  'Lemonsoda',
  'Oransoda',
  'Estathé limone',
  'Estathé pesca',
  'Lipton Ice Tea limone',
  'Lipton Ice Tea pesca',
  'San Benedetto The limone',
  'San Benedetto The pesca',
  'Red Bull',
  'Red Bull Sugarfree',
  'Monster Energy',
  'Monster Ultra',
  'Burn Energy',
  'XL Energy',
  'Schweppes limone',
  'Schweppes tonica',
  'Schweppes ginger beer',
  '7 Up',
  'Dr Pepper',
  'Tè freddo pesca',
  'Tè freddo limone',
]

export const ORDER_SPIRITS_VARIANTS = [
  'Gin Mare',
  "Gin Hendrick's",
  'Gin Bombay Sapphire',
  'Gin Tanqueray',
  "Gin Gordon's",
  'Gin Malfy',
  'Gin Bulldog',
  'Vodka Absolut',
  'Vodka Moskovskaya 38°',
  'Vodka Grey Goose',
  'Vodka Smirnoff',
  'Vodka Belvedere',
  'Rum Havana Club',
  'Rum Bacardi',
  'Rum Diplomatico',
  "Whisky Jack Daniel's",
  'Whisky Jameson',
  'Whisky Ballantines',
  'Whisky Johnnie Walker',
  'Tequila Jose Cuervo',
  'Tequila Patrón',
  'Amaro Averna',
  'Amaro Montenegro',
  'Amaro Lucano',
  'Amaro del Capo',
  'Amaro Cynar',
  'Amaro Braulio',
  'Fernet',
  'Fernet Branca',
  'Jägermeister',
  'Aperol',
  'Campari',
  'Campari soda',
  'Select',
  'Crodino',
  'Martini bianco',
  'Martini rosso',
  'Martini dry',
  'Baileys',
  'Disaronno',
  'Limoncello',
  'Sambuca',
  'Cointreau',
  'Kahlúa',
  'Grand Marnier',
  'Prosecco',
  'Spumante',
  'Champagne',
  'Grappa',
  'Cognac',
  'Brandy',
  'Passoa',
  'Malibu',
  'Southern Comfort',
  'Porto',
  'Sherry',
]

export const ORDER_SUGAR_VARIANTS = [
  'Zucchero bianco',
  'Zucchero di canna',
  'Sciroppo di zucchero liquido',
]

export const ORDER_SALT_VARIANTS = ['Sale fino', 'Sale grosso']

export const ORDER_BAKERY_VARIANTS = [
  'Scrocchiarella Classica',
  'Cornetto Vegano Alemagna',
  'Farina Classica Extra Blu 00',
  'Bustine Fruttil',
  'Cornetto classico',
  'Cornetto integrale',
  'Cornetto al cacao',
  'Cornetto alla crema',
  'Brioche',
  'Brioche integrale',
  'Ciambella',
  'Focaccia',
  'Pane bianco',
  'Pane integrale',
  'Pane multicereali',
  'Grissini',
  'Taralli dolci',
  'Biscotti',
  'Merendine',
  'Torta margherita',
  'Muffin',
  'Croissant',
  'Farina 00',
  'Farina integrale',
  'Farina Manitoba',
  'Lievito',
  'Zucchero a velo',
]

export const ORDER_TRANSPORT_CONTRIBUTION_VARIANTS = [
  'Contributi di trasporto',
  'Contributo di trasporto',
  'Spese di trasporto',
  'Trasporto',
  'Consegna',
]

export const ORDER_BREAKFAST_VARIANTS = [
  'Cornetti alla crema',
  'Treccia alle noci',
  'Brioche',
  'Cornetto classico',
  'Cornetto integrale',
  'Cornetto al cacao',
  'Cornetto alla marmellata',
  'Cornetto al pistacchio',
  'Brioche integrale',
  'Brioche al cacao',
  'Treccia alla crema',
  'Treccia al cacao',
  'Ciambella',
  'Muffin',
  'Croissant',
  'Saccottino',
  'Danese',
  'Merendina',
  'Focaccia dolce',
  'Bombolone',
  'Krapfen',
  'Graffa',
  'Sfogliatella',
  'Cannoncino',
  'Torta margherita',
]

/**
 * Pulsanti rapidi prodotto: `label` = testo pulsante; `variants` = sotto-scelta (es. vini).
 * @type {{ label: string, variants?: string[] }[]}
 */
export const ORDER_QUICK_PRODUCTS = [
  { label: 'Ortaggi', variants: ORDER_VEGETABLE_VARIANTS },
  { label: 'Pasta', variants: ORDER_PASTA_VARIANTS },
  { label: 'Carne', variants: ORDER_MEAT_VARIANTS },
  { label: 'Salumi', variants: ORDER_SALUMI_VARIANTS },
  { label: 'Pesce', variants: ORDER_FISH_VARIANTS },
  { label: 'Frutta', variants: ORDER_FRUIT_VARIANTS },
  { label: 'Latticini', variants: ORDER_DAIRY_VARIANTS },
  { label: 'Formaggi', variants: ORDER_CHEESE_VARIANTS },
  { label: 'Gastronomia', variants: ORDER_GASTRONOMIA_VARIANTS },
  { label: 'Prodotti tipici pugliesi', variants: ORDER_PUGLIA_VARIANTS },
  { label: 'Miele', variants: ORDER_MIELE_VARIANTS },
  { label: 'Cereali', variants: ORDER_CEREAL_VARIANTS },
  { label: 'Legumi', variants: ORDER_LEGUME_VARIANTS },
  { label: 'Zucchero', variants: ORDER_SUGAR_VARIANTS },
  { label: 'Sale', variants: ORDER_SALT_VARIANTS },
  { label: 'Prodotti da forno', variants: ORDER_BAKERY_VARIANTS },
  { label: 'Prodotti da colazione', variants: ORDER_BREAKFAST_VARIANTS },
  { label: 'Contributi di trasporto', variants: ORDER_TRANSPORT_CONTRIBUTION_VARIANTS },
  { label: 'Detersivi', variants: ORDER_DETERGENT_VARIANTS },
  { label: 'Acqua naturale' },
  { label: 'Acqua frizzante' },
  { label: 'Lattine', variants: ORDER_CAN_VARIANTS },
  { label: 'Bevande', variants: ORDER_BEVANDE_VARIANTS },
  { label: 'Ghiaccio', variants: ORDER_ICE_VARIANTS },
  { label: 'Vini', variants: ORDER_WINE_VARIANTS },
  { label: 'Birre', variants: ORDER_BEER_VARIANTS },
  { label: 'Gelati', variants: ORDER_ICE_CREAM_VARIANTS },
  { label: 'Succhi di frutta', variants: ORDER_FRUIT_JUICE_VARIANTS },
  { label: 'Caffè', variants: ORDER_COFFEE_VARIANTS },
  { label: 'Ginseng', variants: ORDER_GINSENG_VARIANTS },
  { label: 'Tè e infusi', variants: ORDER_TEA_INFUSION_VARIANTS },
  { label: 'Accessori per il bar', variants: ORDER_BAR_ACCESSORIES_VARIANTS },
  { label: 'Orzo decaffeinato' },
  { label: 'Patatine', variants: ORDER_CHIPS_VARIANTS },
  { label: 'Alcolici', variants: ORDER_SPIRITS_VARIANTS },
]
